sudo: false

language: go

matrix:
  include:
    - go: 1.4

install:
  - go get github.com/tools/godep
  - ./hack/travis/install-etcd.sh
  - ./hack/build-go.sh

script:
  - ./hack/verify-gofmt.sh
  - ./hack/verify-boilerplate.sh
  - ./hack/verify-description.sh
  - PATH=$GOPATH/bin:$PATH ./hack/verify-generated-conversions.sh
  - PATH=$GOPATH/bin:$PATH ./hack/verify-generated-deep-copies.sh
  - PATH=$GOPATH/bin:./third_party/etcd:$PATH ./hack/verify-gendocs.sh
  - PATH=$GOPATH/bin:./third_party/etcd:$PATH ./hack/verify-swagger-spec.sh
  - godep go test ./cmd/mungedocs

notifications:
  irc: "chat.freenode.net#google-containers"
