---
- name: LOGGING | Assures {{ kube_config_dir }}/addons/cluster-logging dir exists
  file: path={{ kube_config_dir }}/addons/cluster-logging state=directory

- name: LOGGING | Download logging files from Kubernetes repo
  get_url:
    url=https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/fluentd-elasticsearch/{{ item }}
    dest="{{ kube_config_dir }}/addons/cluster-logging/"
    force=yes
  with_items:
    - es-controller.yaml
    - es-service.yaml
    - kibana-controller.yaml
    - kibana-service.yaml
